# Images Category

In [1]:
import os
import numpy as np
import pandas as pd
from tqdm import tqdm
tqdm.pandas()
import shutil
import zipfile
import warnings
warnings.filterwarnings('ignore')


output_dir = f"/content/drive/MyDrive/logo_recognition_similarity_search_project/output"
os.makedirs(output_dir,exist_ok=True)
images_category_dir = f"{output_dir}/images_category"
os.makedirs(images_category_dir,exist_ok=True)

zip_images_dir = f"/content/drive/MyDrive/Data/images_128x128_new.zip"
n_components=600
ds_path = f"{output_dir}/logo-recognition-with-{n_components}-hdbscan-category.tsv"



---

In [ ]:
df = pd.read_csv(ds_path,sep="\t")
df.head()

,id,path,prompt,category
0,1104391803911815278,images/00/00/1104391803911815278_0_0.png,cute simple baby shark logo for company,197906
1,1104391803911815278,images/00/00/1104391803911815278_0_1.png,cute simple baby shark logo for company,197906
2,1104391803911815278,images/00/00/1104391803911815278_1_0.png,cute simple baby shark logo for company,197906
3,1104391803911815278,images/00/00/1104391803911815278_1_1.png,cute simple baby shark logo for company,197906
4,1132464139621646377,images/00/00/1132464139621646377_0_0.png,"food truck, sells french fries, logo on side i...",127006

In [ ]:
import zipfile

with zipfile.ZipFile(zip_images_dir, 'r') as zip_ref:
    zip_ref.extractall('/content')

In [ ]:
df["path_category"] = df.progress_apply(lambda row: os.path.join("images_category",
                                                                 f"category_{row['category']}",
                                                                 os.path.basename(row["path"])
                                                                 ), axis=1)

100%|██████████| 1777584/1777584 [00:22<00:00, 79954.66it/s]

In [ ]:
df.head()

,id,path,prompt,category,path_category
0,1104391803911815278,images/00/00/1104391803911815278_0_0.png,cute simple baby shark logo for company,197906,images_category/category_197906/11043918039118...
1,1104391803911815278,images/00/00/1104391803911815278_0_1.png,cute simple baby shark logo for company,197906,images_category/category_197906/11043918039118...
2,1104391803911815278,images/00/00/1104391803911815278_1_0.png,cute simple baby shark logo for company,197906,images_category/category_197906/11043918039118...
3,1104391803911815278,images/00/00/1104391803911815278_1_1.png,cute simple baby shark logo for company,197906,images_category/category_197906/11043918039118...
4,1132464139621646377,images/00/00/1132464139621646377_0_0.png,"food truck, sells french fries, logo on side i...",127006,images_category/category_127006/11324641396216...



---

In [ ]:
for _, row in tqdm(df.iterrows(), total=len(df), desc="Moving Files"):
    category_folder = os.path.dirname(row["path_category"])
    os.makedirs(category_folder, exist_ok=True)
    path = row["path"]
    path = os.path.join('/content/images_128x128_new/images_128x128',*path.split('/')[1:])
    path_category = row["path_category"]
    shutil.move(path, path_category)

Moving Files: 100%|██████████| 1777584/1777584 [06:11<00:00, 4781.60it/s]

In [ ]:
category_counts = {cat: len(os.listdir(os.path.join("images_category", cat)))
                   for cat in os.listdir("images_category")}

category_counts

{'category_172739': 5,
 'category_152820': 2,
 'category_152973': 28,
 'category_206041': 15,
 'category_12000': 5,
 'category_87859': 5,
 'category_65860': 2,
 'category_126331': 2,
 'category_197134': 4,
 'category_60894': 2,
 'category_14838': 9,
 'category_143724': 2,
 'category_84072': 5,
 'category_89827': 3,
 'category_185266': 42,
 'category_189953': 4,
 'category_115187': 4,
 'category_134052': 6,
 'category_203848': 19,
 'category_70532': 2,
 'category_197224': 8,
 'category_77463': 3,
 'category_90032': 2,
 'category_131528': 2,
 'category_105672': 5,
 'category_29639': 2,
 'category_31100': 4,
 'category_477': 6,
 'category_6808': 5,
 'category_57095': 4,
 'category_75264': 2,
 'category_66453': 2,
 'category_39590': 2,
 'category_155134': 2,
 'category_174934': 2,
 'category_189187': 2,
 'category_112899': 8,
 'category_158692': 3,
 'category_150466': 3,
 'category_27155': 2,
 'category_122325': 2,
 'category_174233': 2,
 'category_130005': 6,
 'category_130283': 7,
 'category_56674': 2,
 'category_21190': 12,
 'category_173978': 4,
 'category_55244': 12,
 'category_204929': 8,
 'category_50665': 7,
 'category_98295': 4,
 'category_141451': 49,
 'category_179881': 2,
 'category_201035': 6,
 'category_190319': 2,
 'category_83263': 7,
 'category_71953': 2,
 'category_58481': 2,
 'category_56201': 3,
 'category_191753': 3,
 'category_151656': 25,
 'category_31805': 2,
 'category_41653': 2,
 'category_10584': 7,
 'category_192616': 2,
 'category_64782': 2,
 'category_148841': 2,
 'category_57697': 2,
 'category_33007': 4,
 'category_37962': 4,
 'category_31504': 3,
 'category_95491': 3,
 'category_121331': 7,
 'category_130978': 4,
 'category_17536': 2,
 'category_64463': 3,
 'category_70064': 6,
 'category_49867': 2,
 'category_206267': 12,
 'category_107613': 3,
 'category_77784': 2,
 'category_168035': 6,
 'category_144779': 23,
 'category_53761': 2,
 'category_55135': 5,
 'category_138177': 2,
 'category_152729': 3,
 'category_34185': 4,
 'category_155503': 24,
 'category_119086': 2,
 'category_131000': 2,
 'category_48859': 3,
 'category_85288': 4,
 'category_53458': 4,
 'category_9259': 3,
 'category_27553': 2,
 'category_36862': 5,
 'category_189920': 2,
 'category_98735': 2,
 'category_170536': 3,
 'category_149524': 4,
 'category_68798': 2,
 'category_25446': 10,
 'category_25110': 3,
 'category_135054': 4,
 'category_65936': 2,
 'category_167339': 2,
 'category_121144': 2,
 'category_3752': 2,
 'category_64810': 12,
 'category_144420': 2,
 'category_70382': 3,
 'category_66769': 8,
 'category_173806': 5,
 'category_119067': 2,
 'category_182806': 2,
 'category_202544': 2,
 'category_61900': 3,
 'category_158141': 2,
 'category_11496': 2,
 'category_189043': 9,
 'category_190247': 9,
 'category_191712': 2,
 'category_102630': 3,
 'category_44195': 2,
 'category_196281': 4,
 'category_3700': 3,
 'category_149861': 2,
 'category_60515': 4,
 'category_179948': 3,
 'category_169742': 2,
 'category_19872': 4,
 'category_136512': 2,
 'category_1314': 2,
 'category_118859': 6,
 'category_162787': 6,
 'category_52470': 2,
 'category_201154': 4,
 'category_18734': 2,
 'category_50909': 2,
 'category_106564': 3,
 'category_53353': 16,
 'category_198437': 3,
 'category_191815': 12,
 'category_100082': 4,
 'category_184884': 3,
 'category_86351': 5,
 'category_182414': 3,
 'category_136132': 2,
 'category_196403': 6,
 'category_184980': 5,
 'category_107617': 15,
 'category_156008': 7,
 'category_3148': 7,
 'category_18066': 2,
 'category_188927': 2,
 'category_20365': 2,
 'category_78556': 5,
 'category_135457': 2,
 'category_35167': 14,
 'category_135199': 3,
 'category_137607': 7,
 'category_21623': 2,
 'category_113728': 2,
 'category_161465': 4,
 'category_11820': 24,
 'category_18585': 17,
 'category_14485': 3,
 'category_85162': 2,
 'category_53091': 2,
 'category_60783': 5,
 'category_70930': 4,
 'category_94272': 2,
 'category_57148': 8,
 'category_149076': 3,
 'category_92794': 6,
 'category_137935': 3,
 'category_30723': 8,
 'category_193718': 3,
 'category_192582': 3,
 'category_199237': 4,
 'category_173813': 9,
 'category_70224': 2,
 'category_29161': 11,
 'category_106180': 4,
 'category_89193': 5,
 'category_123980': 2,
 'category_102321': 2,
 'category_160427': 2,
 'category_178816': 6,
 'category_122626': 2,
 'category_72162': 8,
 'category_45063': 2,
 'category_66611': 3,
 'category_175516': 2,
 'category_193624': 2,
 'category_83776': 4,
 'category_23342': 7,
 'category_83590': 2,
 'category_46805': 4,
 'category_52184': 6,
 'category_169824': 5,
 'category_161185': 2,
 'category_166580': 4,
 'category_133717': 2,
 'category_9053': 7,
 'category_27387': 2,
 'category_117518': 5,
 'category_94605': 5,
 'category_119397': 6,
 'category_100590': 6,
 'category_43470': 2,
 'category_199472': 2,
 'category_163869': 7,
 'category_21537': 4,
 'category_182371': 5,
 'category_58673': 12,
 'category_37428': 2,
 'category_63980': 2,
 'category_102609': 3,
 'category_203429': 6,
 'category_53900': 10,
 'category_90975': 3,
 'category_83800': 4,
 'category_87415': 5,
 'category_108448': 2,
 'category_116264': 2,
 'category_70326': 2,
 'category_76229': 11,
 'category_131873': 2,
 'category_10428': 2,
 'category_136064': 3,
 'category_175664': 2,
 'category_128308': 2,
 'category_21079': 2,
 'category_116274': 6,
 'category_809': 2,
 'category_113186': 2,
 'category_120015': 2,
 'category_101170': 3,
 'category_49498': 5,
 'category_169378': 3,
 'category_35544': 6,
 'category_20081': 2,
 'category_194164': 7,
 'category_127098': 2,
 'category_179229': 2,
 'category_52021': 5,
 'category_135595': 3,
 'category_116937': 2,
 'category_116213': 10,
 'category_100781': 19,
 'category_127341': 6,
 'category_158377': 2,
 'category_124148': 5,
 'category_148203': 3,
 'category_82176': 3,
 'category_127111': 11,
 'category_28473': 2,
 'category_36558': 3,
 'category_13811': 2,
 'category_103345': 2,
 'category_200821': 2,
 'category_3501': 2,
 'category_188111': 3,
 'category_197259': 6,
 'category_154362': 4,
 'category_97906': 4,
 'category_178977': 4,
 'category_61337': 3,
 'category_6010': 7,
 'category_195884': 17,
 'category_91828': 2,
 'category_50349': 28,
 'category_193966': 8,
 'category_121513': 5,
 'category_33122': 2,
 'category_146444': 2,
 'category_44388': 4,
 'category_190606': 4,
 'category_53498': 5,
 'category_95497': 2,
 'category_92310': 9,
 'category_178239': 2,
 'category_48671': 3,
 'category_57678': 2,
 'category_83678': 2,
 'category_55942': 3,
 'category_198087': 3,
 'category_156288': 2,
 'category_142691': 2,
 'category_12366': 2,
 'category_59153': 6,
 'category_39635': 3,
 'category_205026': 2,
 'category_57715': 4,
 'category_203980': 4,
 'category_131738': 2,
 'category_21752': 4,
 'category_147991': 3,
 'category_45280': 2,
 'category_124859': 2,
 'category_27928': 2,
 'category_187713': 2,
 'category_61339': 2,
 'category_60526': 3,
 'category_90628': 2,
 'category_17630': 2,
 'category_117451': 2,
 'category_154407': 4,
 'category_166463': 2,
 'category_11168': 2,
 'category_86275': 3,
 'category_156217': 6,
 'category_196517': 8,
 'category_165673': 4,
 'category_128373': 2,
 'category_136489': 4,
 'category_65609': 2,
 'category_84041': 2,
 'category_32744': 5,
 'category_191032': 4,
 'category_79245': 4,
 'category_158557': 11,
 'category_41840': 5,
 'category_201208': 4,
 'category_197188': 3,
 'category_160948': 2,
 'category_151105': 2,
 'category_166338': 2,
 'category_83436': 2,
 'category_89241': 6,
 'category_38596': 5,
 'category_126093': 2,
 'category_206670': 2,
 'category_196029': 3,
 'category_133133': 3,
 'category_20778': 5,
 'category_202039': 8,
 'category_50339': 4,
 'category_203700': 2,
 'category_2042': 2,
 'category_63668': 5,
 'category_65354': 9,
 'category_74600': 2,
 'category_61474': 10,
 'category_191222': 20,
 'category_418': 5,
 'category_198605': 3,
 'category_139352': 5,
 'category_74553': 2,
 'category_56595': 6,
 'category_203316': 2,
 'category_140962': 25,
 'category_56022': 4,
 'category_189927': 2,
 'category_102204': 2,
 'category_148515': 7,
 'category_207763': 9,
 'category_107068': 2,
 'category_201472': 3,
 'category_80807': 2,
 'category_31104': 2,
 'category_150195': 2,
 'category_142243': 4,
 'category_81761': 12,
 'category_94410': 2,
 'category_72876': 2,
 'category_12132': 11,
 'category_199055': 5,
 'category_204252': 4,
 'category_65340': 2,
 'category_150359': 4,
 'category_102505': 14,
 'category_165716': 3,
 'category_67554': 4,
 'category_136900': 5,
 'category_44698': 16,
 'category_101807': 4,
 'category_199396': 2,
 'category_167224': 10,
 'category_81163': 2,
 'category_85217': 2,
 'category_23760': 4,
 'category_52928': 2,
 'category_11166': 2,
 'category_176662': 2,
 'category_6165': 5,
 'category_56200': 8,
 'category_49560': 4,
 'category_148368': 3,
 'category_48753': 2,
 'category_39394': 4,
 'category_86809': 3,
 'category_112379': 8,
 'category_172203': 5,
 'category_111687': 2,
 'category_127342': 2,
 'category_143905': 2,
 'category_831': 7,
 'category_23203': 6,
 'category_61823': 2,
 'category_38134': 2,
 'category_69772': 3,
 'category_122535': 2,
 'category_149011': 10,
 'category_43596': 2,
 'category_141683': 7,
 'category_45023': 5,
 'category_38165': 5,
 'category_102127': 7,
 'category_182962': 9,
 'category_52831': 2,
 'category_196677': 4,
 'category_161452': 2,
 'category_76128': 7,
 'category_192710': 3,
 'category_24853': 3,
 'category_193139': 13,
 'category_54486': 6,
 'category_49694': 2,
 'category_201478': 4,
 'category_60580': 3,
 'category_138029': 2,
 'category_107253': 5,
 'category_94736': 4,
 'category_196704': 22,
 'category_71671': 8,
 'category_126830': 5,
 'category_206786': 3,
 'category_1371': 2,
 'category_114213': 5,
 'category_131675': 3,
 'category_56599': 3,
 'category_27965': 2,
 'category_203386': 20,
 'category_162806': 3,
 'category_204258': 22,
 'category_130052': 4,
 'category_203609': 3,
 'category_19941': 6,
 'category_175535': 2,
 'category_151044': 2,
 'category_11246': 7,
 'category_109832': 6,
 'category_49152': 13,
 'category_107765': 2,
 'category_23285': 2,
 'category_131628': 2,
 'category_124203': 2,
 'category_190854': 6,
 'category_182715': 3,
 'category_123665': 2,
 'category_64788': 5,
 'category_135201': 2,
 'category_206684': 9,
 'category_162712': 2,
 'category_59790': 2,
 'category_150009': 4,
 'category_118307': 8,
 'category_35193': 9,
 'category_169947': 14,
 'category_87133': 4,
 'category_184964': 2,
 'category_52863': 2,
 'category_143021': 6,
 'category_14275': 2,
 'category_153119': 2,
 'category_91936': 18,
 'category_10316': 5,
 'category_3875': 2,
 'category_100620': 2,
 'category_27518': 2,
 'category_101090': 2,
 'category_76376': 2,
 'category_203243': 3,
 'category_200158': 6,
 'category_171463': 2,
 'category_85460': 6,
 'category_174311': 2,
 'category_127403': 3,
 'category_142494': 4,
 'category_3210': 2,
 'category_69198': 2,
 'category_129331': 5,
 'category_87049': 2,
 'category_47172': 2,
 'category_116894': 2,
 'category_181760': 2,
 'category_109606': 4,
 'category_148907': 5,
 'category_90676': 2,
 'category_23054': 2,
 'category_189211': 11,
 'category_198569': 2,
 'category_141270': 7,
 'category_172035': 9,
 'category_204556': 2,
 'category_192690': 9,
 'category_29192': 9,
 'category_25015': 5,
 'category_25949': 3,
 'category_195852': 2,
 'category_132169': 3,
 'category_170517': 5,
 'category_26326': 8,
 'category_162947': 5,
 'category_135509': 3,
 'category_43756': 9,
 'category_42975': 5,
 'category_51908': 3,
 'category_165479': 3,
 'category_2060': 2,
 'category_189431': 7,
 'category_140145': 2,
 'category_46633': 7,
 'category_44469': 3,
 'category_110559': 8,
 'category_46012': 3,
 'category_92541': 4,
 'category_166744': 6,
 'category_101524': 2,
 'category_41628': 2,
 'category_83536': 3,
 'category_109698': 2,
 'category_150248': 5,
 'category_153738': 17,
 'category_15894': 24,
 'category_167738': 2,
 'category_40416': 7,
 'category_13532': 8,
 'category_82677': 5,
 'category_7777': 8,
 'category_175219': 2,
 'category_52476': 2,
 'category_154265': 4,
 'category_184333': 4,
 'category_207420': 3,
 'category_207943': 5,
 'category_113612': 2,
 'category_150571': 3,
 'category_49411': 3,
 'category_165924': 5,
 'category_61693': 2,
 'category_55009': 2,
 'category_87764': 2,
 'category_31584': 2,
 'category_171281': 13,
 'category_151519': 28,
 'category_33605': 10,
 'category_88307': 42,
 'category_152370': 5,
 'category_147214': 5,
 'category_133444': 3,
 'category_61129': 3,
 'category_50866': 16,
 'category_87135': 14,
 'category_85277': 5,
 'category_133730': 5,
 'category_181526': 3,
 'category_175430': 5,
 'category_6949': 5,
 'category_39646': 3,
 'category_23138': 4,
 'category_9594': 6,
 'category_143157': 4,
 'category_8097': 3,
 'category_180536': 3,
 'category_16091': 2,
 'category_208766': 7,
 'category_26469': 7,
 'category_35373': 2,
 'category_112767': 2,
 'category_65634': 2,
 'category_137974': 36,
 'category_201870': 9,
 'category_137038': 11,
 'category_137030': 11,
 'category_8387': 6,
 'category_141801': 2,
 'category_93893': 3,
 'category_17512': 11,
 'category_176417': 2,
 'category_180487': 2,
 'category_60639': 9,
 'category_41433': 3,
 'category_178592': 3,
 'category_127818': 2,
 'category_7718': 3,
 'category_36721': 10,
 'category_30578': 8,
 'category_139487': 2,
 'category_176068': 21,
 'category_33548': 3,
 'category_91067': 4,
 'category_187963': 2,
 'category_115100': 3,
 'category_174446': 6,
 'category_49562': 4,
 'category_28266': 5,
 'category_39309': 3,
 'category_42754': 8,
 'category_134578': 6,
 'category_204616': 2,
 'category_145377': 3,
 'category_1470': 10,
 'category_69370': 4,
 'category_57732': 7,
 'category_146926': 3,
 'category_59444': 10,
 'category_43634': 2,
 'category_116834': 5,
 'category_46369': 2,
 'category_55302': 4,
 'category_20590': 2,
 'category_80015': 2,
 'category_26945': 2,
 'category_94582': 9,
 'category_100945': 3,
 'category_54314': 4,
 'category_9105': 6,
 'category_71633': 3,
 'category_182812': 2,
 'category_163143': 2,
 'category_132727': 8,
 'category_68454': 7,
 'category_168387': 3,
 'category_96674': 2,
 'category_129958': 5,
 'category_20629': 3,
 'category_114959': 6,
 'category_62230': 4,
 'category_104101': 4,
 'category_105704': 2,
 'category_205116': 2,
 'category_39534': 3,
 'category_79034': 3,
 'category_8173': 2,
 'category_200791': 8,
 'category_195821': 25,
 'category_3391': 4,
 'category_117580': 2,
 'category_2078': 7,
 'category_3655': 12,
 'category_148579': 2,
 'category_10204': 3,
 'category_167732': 2,
 'category_176656': 2,
 'category_191098': 3,
 'category_45753': 8,
 'category_176799': 15,
 'category_121960': 2,
 'category_84686': 2,
 'category_31421': 42,
 'category_110524': 6,
 'category_48473': 6,
 'category_151907': 5,
 'category_192303': 6,
 'category_80786': 4,
 'category_109107': 3,
 'category_200514': 3,
 'category_126685': 5,
 'category_140649': 4,
 'category_124514': 5,
 'category_145075': 5,
 'category_81790': 3,
 'category_62830': 3,
 'category_102707': 2,
 'category_111979': 2,
 'category_16024': 6,
 'category_79514': 2,
 'category_7081': 17,
 'category_187420': 7,
 'category_168021': 2,
 'category_208822': 9,
 'category_57438': 5,
 'category_135786': 2,
 'category_137439': 2,
 'category_134438': 4,
 'category_3878': 2,
 'category_138071': 8,
 'category_59869': 4,
 'category_69691': 4,
 'category_16465': 2,
 'category_104309': 2,
 'category_132883': 2,
 'category_42064': 3,
 'category_83640': 5,
 'category_56430': 15,
 'category_94496': 5,
 'category_108498': 10,
 'category_181105': 2,
 'category_157084': 6,
 'category_169480': 2,
 'category_138267': 6,
 'category_34055': 3,
 'category_141547': 14,
 'category_198543': 2,
 'category_181444': 9,
 'category_12481': 5,
 'category_183116': 15,
 'category_141064': 4,
 'category_200970': 6,
 'category_91271': 3,
 'category_175814': 2,
 'category_182758': 3,
 'category_18391': 7,
 'category_168181': 3,
 'category_26526': 12,
 'category_206678': 2,
 'category_123878': 2,
 'category_120696': 3,
 'category_135621': 12,
 'category_168692': 2,
 'category_134673': 12,
 'category_147890': 7,
 'category_137116': 2,
 'category_160651': 2,
 'category_84933': 3,
 'category_82462': 3,
 'category_162480': 10,
 'category_126825': 3,
 'category_37980': 3,
 'category_174425': 11,
 'category_51338': 13,
 'category_102080': 3,
 'category_118411': 8,
 'category_39625': 5,
 'category_51290': 2,
 'category_130418': 7,
 'category_68988': 5,
 'category_8624': 5,
 'category_184880': 5,
 'category_177678': 4,
 'category_107669': 4,
 'category_37115': 5,
 'category_290': 12,
 'category_10164': 4,
 'category_97706': 8,
 'category_26535': 2,
 'category_66830': 2,
 'category_80544': 2,
 'category_98698': 7,
 'category_199003': 2,
 'category_118011': 4,
 'category_26947': 2,
 'category_176541': 3,
 'category_100206': 3,
 'category_128377': 5,
 'category_21305': 3,
 'category_130341': 8,
 'category_39891': 4,
 'category_202793': 4,
 'category_22772': 6,
 'category_2819': 4,
 'category_45064': 2,
 'category_75154': 2,
 'category_106590': 2,
 'category_61651': 3,
 'category_22499': 2,
 'category_7103': 2,
 'category_156444': 2,
 'category_143729': 8,
 'category_199148': 9,
 'category_70574': 2,
 'category_73854': 3,
 'category_3038': 2,
 'category_129119': 2,
 'category_128602': 2,
 'category_14141': 2,
 'category_24955': 3,
 'category_18046': 4,
 'category_4011': 2,
 'category_55398': 2,
 'category_38711': 2,
 'category_110404': 8,
 'category_30182': 2,
 'category_140333': 3,
 'category_27137': 2,
 'category_123528': 2,
 'category_149493': 7,
 'category_187255': 5,
 'category_39861': 2,
 'category_142217': 4,
 'category_82507': 2,
 'category_206124': 2,
 'category_23924': 6,
 'category_168301': 11,
 'category_55488': 6,
 'category_179899': 3,
 'category_91684': 2,
 'category_13355': 3,
 'category_109100': 8,
 'category_7754': 2,
 'category_194451': 2,
 'category_104811': 6,
 'category_74297': 4,
 'category_52959': 4,
 'category_202056': 2,
 'category_11993': 2,
 'category_96338': 3,
 'category_164708': 5,
 'category_976': 2,
 'category_103685': 3,
 'category_94970': 5,
 'category_158571': 15,
 'category_78358': 2,
 'category_105182': 2,
 'category_146018': 2,
 'category_126971': 29,
 'category_89472': 6,
 'category_3614': 4,
 'category_85591': 4,
 'category_86210': 2,
 'category_34991': 4,
 'category_102880': 6,
 'category_81816': 3,
 'category_173499': 6,
 'category_100200': 19,
 'category_1192': 2,
 'category_125820': 12,
 'category_38292': 14,
 'category_169182': 2,
 'category_19083': 2,
 'category_154659': 7,
 'category_142213': 4,
 'category_148407': 3,
 'category_7317': 2,
 'category_119578': 4,
 'category_83134': 3,
 'category_58868': 2,
 'category_105997': 4,
 'category_109854': 2,
 'category_192479': 6,
 'category_29847': 11,
 'category_174392': 7,
 'category_144224': 3,
 'category_98668': 30,
 'category_185804': 2,
 'category_114516': 4,
 'category_94942': 7,
 'category_42387': 7,
 'category_207015': 3,
 'category_96368': 2,
 'category_131350': 2,
 'category_190796': 2,
 'category_3612': 7,
 'category_83163': 2,
 'category_138139': 2,
 'category_110070': 3,
 'category_174999': 2,
 'category_21192': 12,
 'category_150927': 5,
 'category_175987': 2,
 'category_175549': 13,
 'category_115154': 2,
 'category_37177': 4,
 'category_174877': 2,
 'category_163218': 10,
 'category_108739': 2,
 'category_188503': 2,
 'category_119955': 3,
 'category_140294': 5,
 'category_86883': 11,
 'category_198232': 9,
 'category_163860': 3,
 'category_74287': 3,
 'category_34704': 4,
 'category_147478': 2,
 'category_137807': 2,
 'category_198172': 20,
 'category_61492': 49,
 'category_120219': 13,
 'category_143785': 2,
 'category_36632': 6,
 'category_191134': 2,
 'category_44079': 4,
 'category_26706': 2,
 'category_162074': 4,
 'category_111442': 3,
 'category_154737': 3,
 'category_198194': 3,
 'category_78092': 6,
 'category_191079': 4,
 'category_60445': 2,

In [ ]:
len(category_counts)

209310



---

In [ ]:
df.to_csv(f"{output_dir}/final-logo-recognition-with-{n_components}-hdbscan-category.tsv",sep="\t",index=False)

In [ ]:
df = pd.read_csv(f"{output_dir}/final-logo-recognition-with-{n_components}-hdbscan-category.tsv",sep="\t")
df

,id,path,prompt,category,path_category
0,1104391803911815278,images/00/00/1104391803911815278_0_0.png,cute simple baby shark logo for company,197906,images_category/category_197906/11043918039118...
1,1104391803911815278,images/00/00/1104391803911815278_0_1.png,cute simple baby shark logo for company,197906,images_category/category_197906/11043918039118...
2,1104391803911815278,images/00/00/1104391803911815278_1_0.png,cute simple baby shark logo for company,197906,images_category/category_197906/11043918039118...
3,1104391803911815278,images/00/00/1104391803911815278_1_1.png,cute simple baby shark logo for company,197906,images_category/category_197906/11043918039118...
4,1132464139621646377,images/00/00/1132464139621646377_0_0.png,"food truck, sells french fries, logo on side i...",127006,images_category/category_127006/11324641396216...
...,...,...,...,...,...
1777579,1103397449273462784,images/ff/ff/1103397449273462784_1_1.png,the main idea of the logo is to transmit leade...,209298,images_category/category_209298/11033974492734...
1777580,1123713960366063636,images/ff/ff/1123713960366063636_0_0.png,question mark chess tools logo for instagram a...,171555,images_category/category_171555/11237139603660...
1777581,1123713960366063636,images/ff/ff/1123713960366063636_0_1.png,question mark chess tools logo for instagram a...,171555,images_category/category_171555/11237139603660...
1777582,1123713960366063636,images/ff/ff/1123713960366063636_1_0.png,question mark chess tools logo for instagram a...,171555,images_category/category_171555/11237139603660...
1777583,1123713960366063636,images/ff/ff/1123713960366063636_1_1.png,question mark chess tools logo for instagram a...,171555,images_category/category_171555/11237139603660...



---

In [ ]:
import shutil

shutil.make_archive("images_category", 'zip', "images_category",verbose=1)
print("Done")

Done

In [2]:
from huggingface_hub import HfApi
from google.colab import userdata

HF_TOKEN = userdata.get('HF_TOKEN')
HF_USERNAME = userdata.get('HF_USERNAME')

api = HfApi(token=HF_TOKEN)

repo_id = f"{HF_USERNAME}/images-category"
repo = api.create_repo(repo_id=repo_id, private=True, exist_ok=True, repo_type="dataset")
repo

RepoUrl('https://huggingface.co/datasets/mlproject5606/images-category', endpoint='https://huggingface.co', repo_type='dataset', repo_id='mlproject5606/images-category')

In [ ]:
api.upload_file(
    path_or_fileobj="/content/images_category.zip",
    path_in_repo="images_category.zip",
    repo_id=repo_id,
    repo_type="dataset"
    )

images_category.zip:   0%|          | 0.00/37.5G [00:00<?, ?B/s]

CommitInfo(commit_url='https://huggingface.co/datasets/mlproject5606/images-category/commit/31a931e9ce47134c22229d606e7d912de3b1ca25', commit_message='Upload images_category.zip with huggingface_hub', commit_description='', oid='31a931e9ce47134c22229d606e7d912de3b1ca25', pr_url=None, repo_url=RepoUrl('https://huggingface.co/datasets/mlproject5606/images-category', endpoint='https://huggingface.co', repo_type='dataset', repo_id='mlproject5606/images-category'), pr_revision=None, pr_num=None)

In [3]:
api.upload_file(
    path_or_fileobj=f"{output_dir}/final-logo-recognition-with-{n_components}-hdbscan-category.tsv",
    path_in_repo=f"final-logo-recognition-with-{n_components}-hdbscan-category.tsv",
    repo_id=repo_id,
    repo_type="dataset"
    )

final-logo-recognition-with-600-hdbscan-category.tsv:   0%|          | 0.00/469M [00:00<?, ?B/s]

CommitInfo(commit_url='https://huggingface.co/datasets/mlproject5606/images-category/commit/f13bb75f1a6486b1ee361648a8c1404edf5c00da', commit_message='Upload final-logo-recognition-with-600-hdbscan-category.tsv with huggingface_hub', commit_description='', oid='f13bb75f1a6486b1ee361648a8c1404edf5c00da', pr_url=None, repo_url=RepoUrl('https://huggingface.co/datasets/mlproject5606/images-category', endpoint='https://huggingface.co', repo_type='dataset', repo_id='mlproject5606/images-category'), pr_revision=None, pr_num=None)

In [4]:
api.upload_file(
    path_or_fileobj=f"{output_dir}/reduced_{n_components}_embeddings.npy",
    path_in_repo=f"reduced_{n_components}_embeddings.npy",
    repo_id=repo_id,
    repo_type="dataset"
    )

reduced_600_embeddings.npy:   0%|          | 0.00/4.27G [00:00<?, ?B/s]

CommitInfo(commit_url='https://huggingface.co/datasets/mlproject5606/images-category/commit/889dca3d3b753bf4d83b676894a5e54d30ada6ac', commit_message='Upload reduced_600_embeddings.npy with huggingface_hub', commit_description='', oid='889dca3d3b753bf4d83b676894a5e54d30ada6ac', pr_url=None, repo_url=RepoUrl('https://huggingface.co/datasets/mlproject5606/images-category', endpoint='https://huggingface.co', repo_type='dataset', repo_id='mlproject5606/images-category'), pr_revision=None, pr_num=None)

In [5]:
api.upload_file(
    path_or_fileobj=f"{output_dir}/hdbscan_{n_components}_model.joblib",
    path_in_repo=f"hdbscan_{n_components}_model.joblib",
    repo_id=repo_id,
    repo_type="dataset"
    )

hdbscan_600_model.joblib:   0%|          | 0.00/4.38G [00:00<?, ?B/s]

CommitInfo(commit_url='https://huggingface.co/datasets/mlproject5606/images-category/commit/ea908bae260902827a4f60f5c20730749d25896b', commit_message='Upload hdbscan_600_model.joblib with huggingface_hub', commit_description='', oid='ea908bae260902827a4f60f5c20730749d25896b', pr_url=None, repo_url=RepoUrl('https://huggingface.co/datasets/mlproject5606/images-category', endpoint='https://huggingface.co', repo_type='dataset', repo_id='mlproject5606/images-category'), pr_revision=None, pr_num=None)

In [6]:
api.upload_file(
    path_or_fileobj=f"{output_dir}/hdbscan_{n_components}_outliers_model.joblib",
    path_in_repo=f"hdbscan_{n_components}_outliers_model.joblib",
    repo_id=repo_id,
    repo_type="dataset"
    )

hdbscan_600_outliers_model.joblib:   0%|          | 0.00/1.83G [00:00<?, ?B/s]

CommitInfo(commit_url='https://huggingface.co/datasets/mlproject5606/images-category/commit/f9356372025d0e7a059293b7d9064eb4451880d7', commit_message='Upload hdbscan_600_outliers_model.joblib with huggingface_hub', commit_description='', oid='f9356372025d0e7a059293b7d9064eb4451880d7', pr_url=None, repo_url=RepoUrl('https://huggingface.co/datasets/mlproject5606/images-category', endpoint='https://huggingface.co', repo_type='dataset', repo_id='mlproject5606/images-category'), pr_revision=None, pr_num=None)



---

In [ ]:
import shutil

shutil.move("/content/images_category.zip",f"{images_category_dir}/images_category.zip")
print("Done")

Done