# Prompts Embedding

## Imports

In [3]:
!pip install -U sentence-transformers datasets --quiet

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 487.4/487.4 kB 8.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 8.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 143.5/143.5 kB 10.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 3.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 58.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 52.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 28.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 1.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 5.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 12.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 6.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 4.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 72.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.8/194.8 kB 14.0 MB/s eta 0:00:00

In [4]:
import pandas as pd
import numpy as np
from tqdm import tqdm
tqdm.pandas()

import matplotlib.pyplot as plt
import seaborn as sns
import os
import torch
import transformers
import random
from sentence_transformers import SentenceTransformer

import warnings
warnings.filterwarnings('ignore')


images_dir = "/content/drive/MyDrive/Data/images_128x128_new.zip"
captions_path = "/content/drive/MyDrive/Data/logo_image_caption.tsv"
output_dir = "/content/drive/MyDrive/logo_recognition_similarity_search_project/output"
os.makedirs(output_dir, exist_ok=True)

## Data Exploration


### Laod dataset

In [5]:
raw_df = pd.read_csv(captions_path, sep='\t')
raw_df.id = raw_df.id.apply(lambda x: str(x).strip().lower())
raw_df.head()

,id,path,prompt
0,1068157504917352548,images/8b/5d/1068157504917352548_0_0.png,an Executive Agenda logo containing a pen
1,1068157504917352548,images/8b/5d/1068157504917352548_0_1.png,an Executive Agenda logo containing a pen
2,1068157504917352548,images/8b/5d/1068157504917352548_1_0.png,an Executive Agenda logo containing a pen
3,1068157504917352548,images/8b/5d/1068157504917352548_1_1.png,an Executive Agenda logo containing a pen
4,1068157546126377001,images/18/ef/1068157546126377001_0_0.png,minimalistic flat logo for private equity firm...

### Exploratory & Preprocessing

In [ ]:
raw_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1777584 entries, 0 to 1777583
Data columns (total 3 columns):
 #   Column  Dtype
---  ------  -----
 0   id      object
 1   path    object
 2   prompt  object
dtypes: object(3)
memory usage: 40.7+ MB

In [ ]:
raw_df.describe(include='all').T

          count   unique                                       top freq
id      1777584   444396                       1068157504917352548    4
path    1777584  1777584  images/8b/5d/1068157504917352548_0_0.png    1
prompt  1777584   282276                                      logo  732

In [ ]:
import re

def clean_text(text):
  """
    Cleans a given text by removing non-english characters. Converts text to lowercase.

    Args:
        text (str): The input text.

    Returns:
        str: The cleaned text. Returns an empty string if input is not a string.
    """

  if not isinstance(text, str):
    return ""
  text = re.sub(r'[^\x00-\x7F]+', ' ', text)
  text = text.lower()
  text = text.strip()

  return text

In [ ]:
raw_df['prompt'] = raw_df['prompt'].progress_apply(clean_text)

100%|██████████| 1777584/1777584 [00:08<00:00, 218027.51it/s]

In [ ]:
raw_df.describe(include='all').T

          count   unique                                       top  freq
id      1777584   444396                       1068157504917352548     4
path    1777584  1777584  images/8b/5d/1068157504917352548_0_0.png     1
prompt  1777584   281151                                      logo  1256

In [ ]:
raw_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1777584 entries, 0 to 1777583
Data columns (total 3 columns):
 #   Column  Dtype
---  ------  -----
 0   id      object
 1   path    object
 2   prompt  object
dtypes: object(3)
memory usage: 40.7+ MB

In [ ]:
raw_df.head()

,id,path,prompt
0,1068157504917352548,images/8b/5d/1068157504917352548_0_0.png,an executive agenda logo containing a pen
1,1068157504917352548,images/8b/5d/1068157504917352548_0_1.png,an executive agenda logo containing a pen
2,1068157504917352548,images/8b/5d/1068157504917352548_1_0.png,an executive agenda logo containing a pen
3,1068157504917352548,images/8b/5d/1068157504917352548_1_1.png,an executive agenda logo containing a pen
4,1068157546126377001,images/18/ef/1068157546126377001_0_0.png,minimalistic flat logo for private equity firm...

## Prompts Embedding

In [ ]:
from sentence_transformers import SentenceTransformer
import datasets
import torch

model_id = 'sentence-transformers/all-MiniLM-L6-v2'
device = 'cuda' if torch.cuda.is_available() else 'cpu'

In [ ]:
# convert raw_df to datasets
ds = datasets.Dataset.from_pandas(raw_df)
ds

Dataset({
    features: ['id', 'path', 'prompt'],
    num_rows: 1777584
})

In [ ]:
# Load model from HuggingFace Hub
model = SentenceTransformer(model_id,device=device)

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.7k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

1_Pooling%2Fconfig.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [ ]:
model

SentenceTransformer(
  (0): Transformer({'max_seq_length': 256, 'do_lower_case': False}) with Transformer model: BertModel
  (1): Pooling({'word_embedding_dimension': 384, 'pooling_mode_cls_token': False, 'pooling_mode_mean_tokens': True, 'pooling_mode_max_tokens': False, 'pooling_mode_mean_sqrt_len_tokens': False, 'pooling_mode_weightedmean_tokens': False, 'pooling_mode_lasttoken': False, 'include_prompt': True})
  (2): Normalize()
)

In [ ]:
def batch_encode(examples):
  encoded_prompts = model.encode(examples["prompt"], show_progress_bar=False)
  return {'encoded_prompt': encoded_prompts}

In [ ]:
encoded_prompts_ds = ds.map(
                            batch_encode,
                            batched=True,
                            batch_size=1000,
                            desc="Encoding prompts"
                            )

Encoding prompts:   0%|          | 0/1777584 [00:00<?, ? examples/s]

In [ ]:
# Save the encoded dataset
encoded_prompts_ds.save_to_disk(os.path.join(output_dir, "encoded_prompts_dataset"))

Saving the dataset (0/7 shards):   0%|          | 0/1777584 [00:00<?, ? examples/s]

In [ ]:
encoded_prompts_ds

Dataset({
    features: ['id', 'path', 'prompt', 'encoded_prompt'],
    num_rows: 1777584
})

## Load Encoded Prompts Dataset

In [ ]:
import datasets
import os

ds_path = os.path.join(output_dir, "encoded_prompts_dataset")

ds = datasets.load_from_disk(ds_path)
ds

Dataset({
    features: ['id', 'path', 'prompt', 'encoded_prompt'],
    num_rows: 1777584
})

In [ ]:
print("Shape of the dataset: ", ds.shape)

Shape of the dataset:  (1777584, 4)

In [ ]:
print(ds[0])

{'id': '1068157504917352548', 'path': 'images/8b/5d/1068157504917352548_0_0.png', 'prompt': 'an executive agenda logo containing a pen', 'encoded_prompt': [0.02813463844358921, 0.08543377369642258, 0.06893604248762131, -0.003884686157107353, 0.0654783844947815, 0.005106073804199696, 0.061847977340221405, -0.033956725150346756, 0.12158887833356857, 0.007636446971446276, -0.015827639028429985, 0.07711935043334961, -0.09344757348299026, 0.019994154572486877, 0.0006775992806069553, -0.04366626590490341, -0.04798804968595505, -0.10249566286802292, -0.0020336564630270004, 0.031133590266108513, 0.052370306104421616, 0.006414209492504597, 0.052758194506168365, -0.03269697725772858, -0.05180355906486511, 0.07506828755140305, -0.013911547139286995, -0.02790258079767227, -0.0020461943931877613, -0.03008561208844185, 0.07808278501033783, -0.04226216673851013, 0.02046051062643528, -0.014623149298131466, 0.08209598809480667, 0.002786512253805995, 0.03839430958032608, 0.013472510501742363, 0.0874830111861229, -0.039884570986032486, 0.020670365542173386, -0.08477101475000381, 0.03546009957790375, -0.012774841859936714, -0.001804141909815371, 0.043707914650440216, -0.018310027197003365, 0.0779343992471695, -0.03301404044032097, -0.03174365684390068, 0.0495234839618206, -0.1521213948726654, 0.005678949877619743, -0.10129904747009277, 0.06518855690956116, -0.01825164258480072, 0.05620473250746727, -0.04297224432229996, -0.01703849993646145, -0.05059211701154709, -0.01561703346669674, 0.03994389995932579, -0.05957414582371712, 0.04917837679386139, 0.05297251045703888, 0.04763496294617653, 0.0317649319767952, -0.04942846670746803, -0.014742854982614517, -0.06327708810567856, 0.03885055333375931, -0.030650561675429344, -0.0072995750233531, -0.01216968521475792, 0.013034267351031303, 0.0029868604615330696, 0.035151928663253784, 0.06789856404066086, -0.00011071682820329443, -0.10924429446458817, 0.07224556058645248, 0.033190254122018814, 0.0034968797117471695, 0.05176140367984772, 0.06441954523324966, -0.010934981517493725, -0.04808547720313072, -0.0541723407804966, 0.0026497237849980593, 0.0323200598359108, -0.10062187910079956, -0.008088445290923119, 0.017024517059326172, -0.03412838280200958, -0.05694812536239624, 0.03392649069428444, -0.06284379959106445, -0.02525259740650654, -0.09075254201889038, 0.08503669500350952, 0.008745131082832813, 0.05334509164094925, 0.00839138962328434, -0.047035425901412964, 0.015666909515857697, -0.04499586671590805, -0.02168053202331066, -0.06598681211471558, -0.015811268240213394, 0.014426250010728836, -0.010005420073866844, -0.01886945217847824, -0.0163503959774971, 0.011887207627296448, -0.012648000381886959, -0.14111578464508057, -0.043663833290338516, 0.021428043022751808, 0.10224878042936325, 0.007546147797256708, 0.0026313953567296267, 1.0527264748816378e-05, -0.014141355641186237, -0.03220725059509277, -0.04916132614016533, -0.08520223200321198, 0.002060899743810296, -5.762753056362783e-33, -0.042542193084955215, 0.08633820712566376, -0.05216248705983162, -0.005903757177293301, -0.004935913719236851, 0.07111011445522308, -0.02502320520579815, -0.06738001853227615, -0.021951746195554733, -0.030842842534184456, 0.0396505668759346, 0.04913778230547905, 0.06113576143980026, 0.15550559759140015, 0.01662452705204487, -0.061811912804841995, -0.01702917367219925, 0.08728911727666855, 0.02070600911974907, -0.016187557950615883, -0.04398380592465401, 0.0005093212821520865, -0.020496726036071777, -0.07235363870859146, 0.06317294389009476, 0.029881900176405907, -0.03463359177112579, -0.002078521531075239, 0.021788954734802246, 0.026786910369992256, -0.00815512239933014, 0.012127011083066463, 0.025331461802124977, -0.07614602893590927, -0.014897942543029785, -0.007758196908980608, 0.053542375564575195, -0.10150519013404846, 0.03126893192529678, -0.004500831011682749, 0.016550425440073013, 0.013694215565919876, 0.017997505143284798, 0.08478761464357376, 0.003984508104622364, 0.08470411598682404, 0.011093376204371452, -0.021392766386270523, 0.09695620089769363, -0.036830104887485504, 0.04208539426326752, -0.05671733245253563, 0.004140282515436411, -0.05632859840989113, -0.03402334079146385, -0.11293043196201324, 0.0016122530214488506, -0.027158642187714577, 0.020119041204452515, -0.07907716929912567, 0.07508548349142075, 0.13024286925792694, -0.10249476879835129, 0.07772531360387802, -0.02138632908463478, 0.05111461505293846, -0.06539967656135559, -0.0247440654784441, 0.059964701533317566, -0.010017894208431244, -0.03594590723514557, -0.013038687407970428, 0.10067065060138702, -0.01597093977034092, -0.09600872546434402, 0.0025411508977413177, -0.006712243892252445, 0.0188005194067955, 0.021333130076527596, 0.04026561602950096, -0.056211333721876144, -0.08941635489463806, 0.07535481452941895, -0.10200018435716629, 0.07586938887834549, 0.024148058146238327, 0.08686693757772446, 0.01802014373242855, -0.02529381401836872, 0.006688440218567848, -0.058089833706617355, 0.03181152790784836, 0.011103365570306778, 0.05367380380630493, -0.04474103823304176, 2.8238796097338193e-33, -0.020380951464176178, -0.023733770474791527, 0.032005637884140015, -0.006774597801268101, 0.025575699284672737, 0.04233112558722496, 0.03030986711382866, -0.08637380599975586, -0.03414284437894821, -0.0021797739900648594, 0.013579262420535088, -0.012029300443828106, 0.05045583099126816, 0.016883082687854767, 0.05903857573866844, -0.08524136990308762, 0.011870206333696842, 0.016312476247549057, -0.006404515355825424, 0.0032501844689249992, -0.001357854693196714, 0.03217713534832001, -0.025384660810232162, 0.06359175592660904, -0.016302118077874184, 0.00010923980153165758, 0.07876548171043396, -0.09303150326013565, -0.018948310986161232, 0.014102742075920105, -0.09902326762676239, -0.06181717664003372, -0.03050832264125347, 0.11405184864997864, -0.021899502724409103, 0.03624236211180687, 0.028573457151651382, -0.14398665726184845, -0.08483080565929413, 0.01690278947353363, 0.009375439956784248, -0.02840794064104557, -0.02035880647599697, 0.0888984352350235, -0.049399808049201965, 0.0006263770046643913, -0.10292816907167435, 0.07555226981639862, -0.02014239877462387, 0.06298007071018219, -0.035053886473178864, -0.030129270628094673, 0.006541870068758726, -0.02829631231725216, -0.04512577876448631, 0.025862056761980057, -0.03374478593468666, -0.04412537068128586, 0.09912517666816711, 0.05814309045672417, 0.027950309216976166, 0.044576022773981094, -0.029086505994200706, -0.015291465446352959, 0.07561009377241135, -0.055544380098581314, 0.0159231536090374, 0.027587447315454483, -0.0267367884516716, 0.05767387896776199, 0.03349344804883003, -0.007930697873234749, -0.0662669762969017, -0.03752689063549042, 0.04467117041349411, 0.07599300146102905, 0.03604099527001381, -0.0035069917794317007, -0.06790130585432053, 0.0462971068918705, -0.04478536546230316, 0.0008602260495536029, -0.08789970725774765, -0.0015280465595424175, 0.10555633157491684, -0.018059739843010902, -0.06270819157361984, -0.0724702924489975, -0.03786097839474678, 0.09083744883537292, -0.022565998136997223, 0.0012007722398266196, 0.061811674386262894, 0.08583584427833557, 0.011722039431333542, -1.4457896213571075e-08, -0.013834070414304733, 0.05043022707104683, 0.06829354166984558, -0.07203732430934906, 0.0715089961886406, -0.0555204302072525, 0.008828197605907917, -0.1526898443698883, 0.049366194754838943, -0.007325651589781046, 0.01948285661637783, -0.033554691821336746, -0.10283687710762024, -0.01337424200028181, -0.03475622832775116, 0.002610517665743828, -0.06361354142427444, 0.018133698031306267, -0.018694786354899406, 0.0008372796000912786, 0.017000548541545868, 0.018446726724505424, -0.008850493468344212, -0.10037075728178024, -0.014636687934398651, 0.02185499295592308, 0.02834729477763176, 0.06263162195682526, -0.07618735730648041, 0.03287630155682564, -0.02368258684873581, 0.02224959433078766, 0.043326910585165024, 0.05820323899388313, -0.01190896239131689, -0.0160946287214756, -0.01268408726900816, 0.024715181440114975, 0.03469229117035866, 0.03274393826723099, 0.043799933046102524, -0.021794850006699562, -0.0063554150983691216, 0.006017006002366543, -0.022214144468307495, 0.04859623312950134, 0.008529361337423325, 0.020847516134381294, -0.021844955161213875, -0.0312969870865345, -0.025793684646487236, -0.016728349030017853, -0.007414540741592646, 0.0476464107632637, 0.014519625343382359, -0.02957349829375744, 0.03486343100667, 0.03057136759161949, 0.03175025433301926, 0.016864832490682602, 0.11211621016263962, 0.01949392817914486, -0.0037553345318883657, 0.0019119931384921074]}

In [ ]:
len(ds[0]['encoded_prompt'])

384

In [ ]:
# convert dataset to DataFrame
df = ds.to_pandas()
df.head()

,id,path,prompt,encoded_prompt
0,1068157504917352548,images/8b/5d/1068157504917352548_0_0.png,an executive agenda logo containing a pen,"[0.028134638, 0.08543377, 0.06893604, -0.00388..."
1,1068157504917352548,images/8b/5d/1068157504917352548_0_1.png,an executive agenda logo containing a pen,"[0.028134638, 0.08543377, 0.06893604, -0.00388..."
2,1068157504917352548,images/8b/5d/1068157504917352548_1_0.png,an executive agenda logo containing a pen,"[0.028134638, 0.08543377, 0.06893604, -0.00388..."
3,1068157504917352548,images/8b/5d/1068157504917352548_1_1.png,an executive agenda logo containing a pen,"[0.028134638, 0.08543377, 0.06893604, -0.00388..."
4,1068157546126377001,images/18/ef/1068157546126377001_0_0.png,minimalistic flat logo for private equity firm...,"[0.084999934, 0.04874548, -0.020015288, -0.048..."

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1777584 entries, 0 to 1777583
Data columns (total 4 columns):
 #   Column          Dtype
---  ------          -----
 0   id              object
 1   path            object
 2   prompt          object
 3   encoded_prompt  object
dtypes: object(4)
memory usage: 54.2+ MB

In [ ]:
print("Shape of the dataset: ", df.shape)

Shape of the dataset:  (1777584, 4)



---